version: "3.9"

services:
  postgres:
    container_name: postgres_db_server
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=SA
      - POSTGRES_PASSWORD=msSQL@123
      - POSTGRES_DB=employee
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres:
